data_notes = [{'title': 'Ativação de Cliente'}, {'title': 'Integração de Cliente'}, {'title': 'Alinhamento Interno'}, {
    'title': 'Treinamento'}, {'title': 'FUP DevSecOps'}, {'title': 'Planejamento'}, {'title': 'Ativação de Cliente'}]

data_errors = [{'error_id': 'Error 0x12', 'error_desc': 'Permissão negada', 'error_type': 'Error'}, {'error_id': 'Warning', 'error_desc': 'Envio de e-mail', 'error_type': 'Warning'}, {'error_id': 'Error 0x32',
                                                                                                                                                                                        'error_desc': 'Criação de SIR', 'error_type': 'Error'}, {'error_id': 'Error 0x14', 'error_desc': 'Geração de template', 'error_type': 'Error'}, {'error_id': 'Error 0x12', 'error_desc': 'Execução de Task', 'error_type': 'Error'}]

data_customer = [{'customer_name': 'ACSC', 'siem_name': 'RSA', 'status': 'Activated'}, {'customer_name': 'CARE PLUS', 'siem_name': 'RSA', 'status': 'Activated'}, {'customer_name': 'LEROY MERLIN', 'siem_name': 'RSA', 'status': 'Activated'}, {'customer_name': 'PORTO BANK', 'siem_name': 'Securonix', 'status': 'Activated'}, {'customer_name': 'BOCOM BBM', 'siem_name': 'RSA_NWServer', 'status': 'Activated'}, {
    'customer_name': 'NTS', 'siem_name': 'RSA', 'status': 'Disabled'}, {'customer_name': 'DATASUS', 'siem_name': 'RSA Netwitness', 'status': 'Activated'}, {'customer_name': 'ASSAÍ', 'siem_name': 'RSA_NWServer', 'status': 'Activated'}, {'customer_name': 'SEBREA-PE', 'siem_name': 'Securonix', 'status': 'Activated'}, {'customer_name': 'SEBRAE-MT', 'siem_name': 'Securonix', 'status': 'Activated'}]

data_cases = [{'case_number': 'CS0910290', 'short_description': 'Ativação do Securonix', 'case_date': '2023-02-01'}, {'case_number': 'CS0910291', 'short_description': 'Registro de TimeWorked', 'case_date': '2023-02-01'}, {'case_number': 'CS0910292', 'short_description': 'Integração AbuseIPDB', 'case_date': '2023-02-01'}, {'case_number': 'CS0910293', 'short_description': 'Listagem de Clientes Ativos',
                                                                                                                                                                                                                                                                                                                                    'case_date': '2023-02-01'}, {'case_number': 'CS0910294', 'short_description': 'Otimização de Fluxos Semi-Autos', 'case_date': '2023-02-01'}, {'case_number': 'CS0910295', 'short_description': 'Criação de Fluxos Especificos', 'case_date': '2023-02-01'}, {'case_number': 'CS0910296', 'short_description': 'Ativação do cliente ISH Tecnologia', 'case_date': '2023-02-01'}]

data_tickets = [{"id":"#2023-02-01-1","description":"AD Multiple Failed Logins","customer":"Banestes","owner":"Soar Bot","priority":"Low","status":"Closed","create_date":"2023-02-01"},{"id":"#2023-02-02-2","description":"AD Account Changed","customer":"ISH Tecnologia","owner":"Soar Bot","priority":"Medium","status":"Open","create_date":"2023-02-02"},{"id":"#2023-02-05-3","description":"Possible Malware Detected","customer":"Leroy Merlin","owner":"Soar Bot","priority":"High","status":"Running","create_date":"2023-02-05"},{"id":"#2023-02-06-4","description":"DoS / DDoS Detected and not blocked","customer":"Eletrobras","owner":"Soar Bot","priority":"High","status":"Open","create_date":"2023-02-06"},{"id":"#2023-02-08-5","description":"Suspicious Office365 Login","customer":"Unicid","owner":"Soar Bot","priority":"Medium","status":"Closed","create_date":"2023-02-08"},{"id":"#2023-02-08-6","description":"AD Multiple Failed Logins","customer":"Care Plus","owner":"Soar Bot","priority":"Low","status":"Open","create_date":"2023-02-08"}]
